spring:
  application:
    name: dbuserrepo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: system[user_repo]
    password: Welcome1234##
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: CustomerConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30

  liquibase:
    change-log: classpath:db/changelog/controller.yaml
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    user: SYSTEM
    password: Welcome1234##
    enabled: ${LIQUIBASE_ENABLED:true}


