-- liquibase formatted sql

-- changeset atael:inherit_system endDelimiter:/
DECLARE
  L_CONN_USER   VARCHAR2(255);
  L_USER	    VARCHAR2(255);
  L_TBLSPACE    VARCHAR2(255);
BEGIN
BEGIN
SELECT USER INTO L_CONN_USER FROM DUAL;
SELECT USERNAME INTO L_USER FROM DBA_USERS WHERE USERNAME='USER_REPO';
EXCEPTION WHEN NO_DATA_FOUND THEN
    execute immediate 'CREATE USER "USER_REPO" NO AUTHENTICATION';
END;
execute immediate 'ALTER USER "USER_REPO" GRANT CONNECT THROUGH '||L_CONN_USER;
SELECT DEFAULT_TABLESPACE INTO L_TBLSPACE FROM DBA_USERS WHERE USERNAME='USER_REPO';
execute immediate 'ALTER USER "USER_REPO" QUOTA UNLIMITED ON '||L_TBLSPACE;
execute immediate 'GRANT CONNECT TO "USER_REPO"';
execute immediate 'GRANT RESOURCE TO "USER_REPO"';
execute immediate 'ALTER USER "USER_REPO" DEFAULT ROLE CONNECT,RESOURCE';
END;
/