-- liquibase formatted sql

--changeset atael:aa runAlways:true
--preconditions onFail:MARK_RAN onerror:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM USER_REPO.USERS WHERE 1=2
DROP TABLE USER_REPO.USERS;

--changeset atael:bb runAlways:true
CREATE TABLE USER_REPO.USERS
(
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 20),
    PASSWORD VARCHAR2(255 CHAR),
    ROLES    VARCHAR2(255 CHAR),
    USERNAME VARCHAR2(255 CHAR),
    PRIMARY KEY (USER_ID)
) LOGGING;

COMMENT ON TABLE USER_REPO.USERS is 'KICKING THE TIRES USER REPOSITORY';

--rollback DROP TABLE USER_REPO.USERS;